version: "3.8"
services:
    keycloak-database:
      image: postgres:latest
      container_name: keycloak_db
      expose:
        - "5433"
      ports:
        - "5433:5433"
      volumes:
        - ./db/keycloakDB:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: "keycloak_test"
        POSTGRES_PASSWORD: "keycloak_test"
        POSTGRES_DB: "keycloak"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
      command:
        - "-p 5433"
      networks:
        keycloak-nw:
          aliases:
            - "keycloak_db"
    keycloak:
      image: quay.io/keycloak/keycloak
      container_name: keycloak
      environment:
        KEYCLOAK_ADMIN: guin
        KEYCLOAK_ADMIN_PASSWORD: guin1!
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-database:5433/keycloak
        KC_DB_USERNAME: "keycloak_test"
        KC_DB_PASSWORD: "keycloak_test"
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
      ports:
        - "8082:8080"
      command: start-dev
      healthcheck:
        test: "curl -f http://localhost:8082/admin || exit 1"
      depends_on:
        keycloak-database:
          condition: service_started
      networks:
        keycloak-nw:
          aliases:
            - "keycloak"

networks:
  keycloak-nw:
    driver: bridge