name: 9-in Team 테스트 자동화

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 프로젝트 체크아웃합니다.
        uses: actions/checkout@v3

      - name: 자바 21을 설치합니다.
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: 시간을 서울시간으로 맞춥니다.
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: 그래들 캐시를 삭제합니다.
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: 그래들 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      - name: 프로젝트를 빌드합니다.
        run: ./gradlew clean build

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json

      - name: 코드코브에서 자코코 분석을 해줍니다.
        uses: codecov/codecov-action@v3
        env:
          name: 9in-codecov
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: ./team-service/build/reports/jacoco/test/jacocoTestReport.xml

      - name: 챗봇이 코드리뷰를 해줍니다.
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
